---- create foreign keys
ALTER TABLE attribute ADD CONSTRAINT FKC7AA9CD0AD4F57 FOREIGN KEY (list_of_values_id) REFERENCES list_of_values;
ALTER TABLE attribute ADD CONSTRAINT FKC7AA9C41ACA130 FOREIGN KEY (entity_type_id) REFERENCES entity_type;
ALTER TABLE entity_type ADD CONSTRAINT entity_type_parent_fk FOREIGN KEY (parent_id) REFERENCES entity_type;
ALTER TABLE group_ ADD CONSTRAINT FKB63DD9C041ACA130 FOREIGN KEY (entity_type_id) REFERENCES entity_type;
ALTER TABLE group_attribute ADD CONSTRAINT FK7722C8DC197762CB FOREIGN KEY (attribute_id) REFERENCES attribute;
ALTER TABLE group_attribute ADD CONSTRAINT FK7722C8DCCEDAA46B FOREIGN KEY (group_id) REFERENCES group_;
ALTER TABLE list_item ADD CONSTRAINT FKE15B8B69D0AD4F57 FOREIGN KEY (list_of_values_id) REFERENCES list_of_values;
ALTER TABLE query ADD CONSTRAINT FK66F18C82E866583 FOREIGN KEY (user_id) REFERENCES user_;
ALTER TABLE user_role ADD CONSTRAINT FK143BF46A895BA1A3 FOREIGN KEY (role_id) REFERENCES role;
ALTER TABLE user_role ADD CONSTRAINT FK143BF46A2E866583 FOREIGN KEY (user_id) REFERENCES user_;
